id: A828E5F45
base_file: f5A3A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:00:32.289879
  last_modified_at: 2022-05-30 21:00:32.289902
