id: A828E5F45
base_file: fDB70.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 21:00:32.292535
  last_modified_at: 2022-05-30 21:00:32.292539
